---
name: MasonX-Maypole
version: 0.51
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: use Mason as the frontend and view for Maypole version 2
license: perl
requires:
  HTML::Mason: 1.3
  Maypole: 2.1
  Memoize: 0
  Symbol: 0
  Test::More: 0
provides:
  MasonX::Maypole:
    file: lib/MasonX/Maypole.pm
    version: 0.51
  MasonX::Maypole::ApacheHandler:
    file: lib/MasonX/Maypole.pm
    version: 0.51
  MasonX::Maypole::View:
    file: lib/MasonX/Maypole/View.pm
generated_by: Module::Build version 0.2609
